### ISSUE TITLE
[1.0.3+1.20.4-neoforge] Crash on server start - Calls client-only method

### ISSUE THREAD

**Issue by TigerWalts** [Slexom/animal-feeding-trough#26]
The main mod class' `<init>` method calls it's own `setupClient()` method which is annotated as client-only.

https://github.com/Slexom/animal-feeding-trough/blob/244effbcd9019d7ab58a64f7dce381d0f04b92e1/neoforge/src/main/java/slexom/vf/animal_feeding_trough/platform/neoforge/AnimalFeedingTroughModNeoForge.java#L14-L31

https://mclo.gs/QellinT

**Comment by MSandro** [comment]
I can confirm this issue, same on my server instance
hope it will be fixed soon.
