### ISSUE TITLE
it's working in creative mode but i'm unable to craft in survival.

### ISSUE THREAD

**Issue by Pawnstein** [Slexom/animal-feeding-trough#37]
**LOG:**

`[22:25:23] [Worker-Main-5/ERROR]: Couldn't parse data file 'animal_feeding_trough:feeding_trough' from 'animal_feeding_trough:recipe/feeding_trough.json': DataResult.Error['Map entry '#' : Failed to parse either. First: Input does not contain a key [fabric:type]: MapLike[{"tag":"minecraft:wooden_slabs"}]; Second: Failed to parse either. First: Not a string: {"tag":"minecraft:wooden_slabs"}; Second: Failed to parse either. First: Not a json array: {"tag":"minecraft:wooden_slabs"}; Second: Not a string: {"tag":"minecraft:wooden_slabs"}']
`

**MODS FOLDER:**

![Screenshot_6](https://github.com/user-attachments/assets/29f75c4d-267d-4888-96c5-fa668033fc9f)

**Comment by MrKubb** [comment]
same here
